@startuml sequence

Datファイル -> store_data

store_data -right-> pandas_converter
store_data -down-> 処理対象を選ぶ
store_data -up-> 計算する

class Datファイル

class store_data{
    actual : dataframe
    control : dataframe
    第一引数の値以下から.datを探す()
    datをpandasにする()
}

class pandas_converter{
    delete_lastline()
    delete_arrows()
    rename_columns()
    manage_line(data_type)
}

class 処理対象を選ぶ{
    処理する列
    処理しない列
    データの種類
    0以外が含まれる列を検索する()
}

class 計算する{
    2つの値の差の絶対値を返す()
    - 列ごとの平均値を計算する()
    - 最大値を取得する（）
    - 誤差率を計算する（）
}

class テキストファイル出力{
}

@enduml